services:
  bot:
    image: node:18
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: sh -c "npm ci && node deploy-commands.js && node index.js"
    ports:
      - "4200:4200"
